### ISSUE TITLE
Re-enable "no-undef" eslint rule for type-check

### ISSUE THREAD

**Issue by davidhorak** [briza-insurance/wegood#43]
## Description
- Current version of eslint triggers false errors for User Defined Type Guards:
```
export function isDate (value: unknown): value is Date {
  return value instanceof Date
}
// error  'value' is not defined  no-undef
```
- Reported bug: https://github.com/typescript-eslint/typescript-eslint/issues/2462

When fixed, re-enable the no-undef rule: https://github.com/briza-insurance/wegood/blob/9f36ca2bedb64ef010de0adf806bd85b560de61a/src/common/type-check.ts#L1

**Comment by rthreei** [comment]
I see. Should that be `value: any` instead?

**Comment by davidhorak** [comment]
> I see. Should that be `value: any` instead?

It is this bit ```: value is Date ```, the https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards which triggers the erorr

**Comment by davidhorak** [comment]
> > I see. Should that be `value: any` instead?
> 
> It is this bit `: value is Date `, the https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards which triggers the erorr

the eslint sees the "value" variable as "not defined" regardless its type

**Comment by rthreei** [comment]
Interesting.  Why not disable that lint rule for that line specifically then?

**Comment by davidhorak** [comment]
> Interesting. Why not disable that lint rule for that line specifically then?

Great point, 9f36ca2bedb64ef010de0adf806bd85b560de61a
